In [9]:
import numpy as np

# Input Image (4x4)
image = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [3, 4, 5, 6]
])

# 2x2 Kernel
kernel = np.array([
    [1, 0],
    [0, 1]
])

stride = 1
padding = 1


# Add Padding
padded_image = np.pad(image,
                      ((padding, padding),
                       (padding, padding)),
                      mode='constant')

# im2col Function
def im2col(image, kernel_size, stride):

    rows = []

    out_h = (image.shape[0] - kernel_size) // stride + 1
    out_w = (image.shape[1] - kernel_size) // stride + 1

    for i in range(0, out_h):
        for j in range(0, out_w):

            patch = image[
                i*stride:i*stride+kernel_size,
                j*stride:j*stride+kernel_size
            ]

            rows.append(patch.flatten())

    return np.array(rows)

# Convert Image to Columns
X_col = im2col(padded_image, 2, stride)

# Flatten Kernel
K_col = kernel.flatten()

# Matrix Multiplication
output = np.dot(X_col, K_col)

# Output Shape
out_size = int(np.sqrt(len(output)))
output = output.reshape(out_size, out_size)

# Print Results
print("Original Image:")
print(image)

print("\nPadded Image:")
print(padded_image)

print("\nKernel:")
print(kernel)

print("\nim2col Matrix:")
print(X_col)

print("\nOutput:")
print(output)

Original Image:
[[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]
 [3 4 5 6]]

Padded Image:
[[0 0 0 0 0 0]
 [0 1 2 3 0 0]
 [0 4 5 6 1 0]
 [0 7 8 9 2 0]
 [0 3 4 5 6 0]
 [0 0 0 0 0 0]]

Kernel:
[[1 0]
 [0 1]]

im2col Matrix:
[[0 0 0 1]
 [0 0 1 2]
 [0 0 2 3]
 [0 0 3 0]
 [0 0 0 0]
 [0 1 0 4]
 [1 2 4 5]
 [2 3 5 6]
 [3 0 6 1]
 [0 0 1 0]
 [0 4 0 7]
 [4 5 7 8]
 [5 6 8 9]
 [6 1 9 2]
 [1 0 2 0]
 [0 7 0 3]
 [7 8 3 4]
 [8 9 4 5]
 [9 2 5 6]
 [2 0 6 0]
 [0 3 0 0]
 [3 4 0 0]
 [4 5 0 0]
 [5 6 0 0]
 [6 0 0 0]]

Output:
[[ 1  2  3  0  0]
 [ 4  6  8  4  0]
 [ 7 12 14  8  1]
 [ 3 11 13 15  2]
 [ 0  3  4  5  6]]
