In [24]:
import torch
import torch.nn as nn

# Generator
# -----------------------------
generator = nn.Sequential(
    nn.Linear(10, 20),
    nn.ReLU(),
    nn.Linear(20, 5)
)

# Critic
critic = nn.Sequential(
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 1)
)

# Real Data
real_data = torch.randn(1, 5)

# Random Noise
noise = torch.randn(1, 10)

# Generate Fake Data
fake_data = generator(noise)

# -----------------------------
# Critic Scores
# -----------------------------
real_score = critic(real_data)
fake_score = critic(fake_data)

# Wasserstein Loss
critic_loss = fake_score.mean() - real_score.mean()

generator_loss = -fake_score.mean()

# Simple Gradient Penalty
gradient_penalty = torch.mean((real_score - fake_score) ** 2)

# Total Critic Loss
total_critic_loss = critic_loss + 10 * gradient_penalty

# Results
print("Generated Fake Data")
print(fake_data)

print("\nReal Score")
print(real_score)

print("\nFake Score")
print(fake_score)

print("\nGenerator Loss")
print(generator_loss.item())

print("\nCritic Loss")
print(critic_loss.item())

print("\nGradient Penalty")
print(gradient_penalty.item())

print("\nTotal Critic Loss")
print(total_critic_loss.item())

Generated Fake Data
tensor([[ 0.0944, -0.0979,  0.0839,  0.2324,  0.2690]],
       grad_fn=<AddmmBackward0>)

Real Score
tensor([[0.2805]], grad_fn=<AddmmBackward0>)

Fake Score
tensor([[0.1190]], grad_fn=<AddmmBackward0>)

Generator Loss
-0.11897490918636322

Critic Loss
-0.1615293174982071

Gradient Penalty
0.026091720908880234

Total Critic Loss
0.09938789904117584
