In [14]:
import torch

# Input Data
X = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])

epsilon = 1e-5

# Scale (Gamma) and Shift (Beta)
gamma = torch.ones(3)
beta = torch.zeros(3)

# Running Mean and Variance
running_mean = torch.zeros(3)
running_var = torch.ones(3)

# Batch Normalization
batch_mean = torch.mean(X, dim=0)
batch_var = torch.var(X, dim=0, unbiased=False)

# Update Running Statistics
momentum = 0.9
running_mean = momentum * running_mean + (1 - momentum) * batch_mean
running_var = momentum * running_var + (1 - momentum) * batch_var

# Normalize
X_hat = (X - batch_mean) / torch.sqrt(batch_var + epsilon)

# Scale and Shift
batch_norm = gamma * X_hat + beta

print("Batch Normalization Output")
print(batch_norm)

print("\nRunning Mean")
print(running_mean)

print("\nRunning Variance")
print(running_var)

# ==========================================
# Layer Normalization
# ==========================================

layer_mean = torch.mean(X, dim=1, keepdim=True)
layer_var = torch.var(X, dim=1, keepdim=True, unbiased=False)

X_layer = (X - layer_mean) / torch.sqrt(layer_var + epsilon)

layer_norm = gamma * X_layer + beta

print("\nLayer Normalization Output")
print(layer_norm)


# Manual Backward Pass

# Dummy Gradient from Next Layer
dout = torch.ones_like(batch_norm)

# Gradient of Gamma
dgamma = torch.sum(dout * X_hat, dim=0)

# Gradient of Beta
dbeta = torch.sum(dout, dim=0)

print("\nGradient of Gamma")
print(dgamma)

print("\nGradient of Beta")
print(dbeta)

Batch Normalization Output
tensor([[-1.0000, -1.0000, -1.0000],
        [ 1.0000,  1.0000,  1.0000]])

Running Mean
tensor([0.2500, 0.3500, 0.4500])

Running Variance
tensor([1.1250, 1.1250, 1.1250])

Layer Normalization Output
tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]])

Gradient of Gamma
tensor([0., 0., 0.])

Gradient of Beta
tensor([2., 2., 2.])
